### ISSUE TITLE
Adding Lua Toolbox to MoonRocks

### ISSUE THREAD

**Issue by leafo** [catwell/lua-toolbox#18]
I'd like to start adding the functionality of Lua Toolbox to MoonRocks.

Our stacks are a bit different, you have a pure Lua implementation and use Redis as a database. I'd definitely like to migrate the data you have into Postgres for MoonRocks. I'd also prefer to keep things in MoonScript on my end as well. I don't mind doing all the programming to get the functionality moved over. If you want certain things to work a certain way, like if you have a grand plan for how the ideal Lua Toolbox works, then you should definitely tell me though.

I have two questions:

How do labels work. Have you manually applied all of them?

Endorsements are tied to user accounts, should we have a system to migrate accounts? Are there few enough users where it can be done manually?

**Comment by catwell** [comment]
Closed by https://github.com/luarocks/luarocks-site/pull/86
