### ISSUE TITLE
charset

### ISSUE THREAD

**Issue by MisterDA** [catwell/lua-toolbox#22]
Hi ! It seems that there's no `<meta charset="UTF-8">` tag in your pages, so my Firefox falls back to Occidental encoding instead of UTF-8 and such things as LÖVE are printed as LÃ–VE.
This should do the trick (in [view/layout.moon](https://github.com/catwell/lua-toolbox/blob/master/views/layout.moon)).

``` diff
@@ -4,6 +4,7 @@ class MainLayout extends Widget
   content: =>
     html_5 ->
       head ->
+        meta charset: "UTF-8"
         title @title or "Lua Toolbox"
         link rel: "stylesheet", href: "//fonts.googleapis.com/css?family=Raleway"
         link rel: "stylesheet", href: "//fonts.googleapis.com/css?family=Libre+Baskerville"
```

**Comment by catwell** [comment]
Thank you for the report. IMO it is not something that belongs in the HTML but rather in HTTP headers, so I fixed it by adding `charset: utf-8;` in the nginx config. Tell me if it works for you.

**Comment by catwell** [comment]
Usernames fixed, header set, closing.
